# Generated by Django 3.2 on 2022-08-03 15:39

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gender', models.CharField(blank=True, choices=[['Nam', 'Nam'], ['Nam', 'Nam'], ['Khác/Không trả lời', 'Khác/Không trả lời']], max_length=255, null=True, verbose_name='Giới tính')),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Địa chỉ')),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('dateofbirth', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Ngày sinh')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email address')),
                ('is_lock', models.BooleanField(blank=True, default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': '00. Danh sách người dùng',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated_at')),
                ('customer', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('numberphone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Số điện thoại')),
                ('code', models.CharField(blank=True, max_length=12, null=True, verbose_name='CMT/CCCD')),
                ('age', models.CharField(blank=True, max_length=2, null=True, verbose_name='Tuổi')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nghề nghiệp')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ')),
                ('status', models.CharField(blank=True, choices=[['Không xác định', 'Không xác định'], ['Đang dùng', 'Đang dùng'], ['Chưa dùng', 'Chưa dùng']], default='Chưa dùng', max_length=255, null=True, verbose_name='Tình trạng')),
                ('type', models.CharField(blank=True, choices=[['Không xác định', 'Không xác định'], ['Trẻ em', 'Trẻ em'], ['Người lớn', 'Người lớn'], ['Người già', 'Người già'], ['VIP', 'VIP']], default='Không xác định', max_length=255, null=True, verbose_name='Loại khách hàng')),
                ('image_profile', models.FileField(blank=True, null=True, upload_to='images customer', verbose_name='Hình ảnh hồ sơ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': '06. Khách Hàng',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ngày')),
            ],
            options={
                'verbose_name_plural': '01. Ngày',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated_at')),
                ('product', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('function', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Tác dụng')),
                ('dosage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Liều dùng')),
                ('note', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Lưu ý')),
            ],
            options={
                'verbose_name_plural': '04. Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated_at')),
                ('service', models.CharField(max_length=255, verbose_name='Tên dịch vụ')),
                ('function', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Tác dụng')),
                ('note', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Lưu ý')),
            ],
            options={
                'verbose_name_plural': '05. Dịch vụ',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Buổi')),
            ],
            options={
                'verbose_name_plural': '02. Buổi',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated_at')),
                ('day_re_examination', models.CharField(blank=True, max_length=8, null=True, verbose_name='Ngày tái khám')),
                ('how_to', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cách dùng')),
                ('detail_caleder_examination', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Chi tiết lịch khám')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='Tên khách hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': '10. Đơn kê',
            },
        ),
        migrations.CreateModel(
            name='FileProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_product', models.FileField(upload_to='images product/', verbose_name='Hình ảnh')),
                ('product_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='Hình ảnh sản phẩm')),
            ],
            options={
                'verbose_name_plural': '03. Ảnh sản phẩm ',
            },
        ),
        migrations.CreateModel(
            name='FileOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_before', models.FileField(blank=True, null=True, upload_to='images before', verbose_name='Hình ảnh trước điều trị')),
                ('file_after', models.FileField(blank=True, null=True, upload_to='images after', verbose_name='Hình ảnh sau điều trị')),
                ('img_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order', verbose_name='Hình ảnh đơn kê')),
            ],
            options={
                'verbose_name_plural': '07. Ảnh đơn kê',
            },
        ),
        migrations.CreateModel(
            name='DetailOrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=5, null=True, verbose_name='Thời gian')),
                ('note', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lưu ý')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order', verbose_name='Đơn kê')),
                ('service', models.ManyToManyField(blank=True, to='core.Service', verbose_name='Tên dịch vụ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': '09. Chi tiết các dịch vụ đi trong Đơn kê',
            },
        ),
        migrations.CreateModel(
            name='DetailOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ManyToManyField(blank=True, related_name='list_day', to='core.Day', verbose_name='Ngày')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order', verbose_name='Đơn kê')),
                ('product', models.ManyToManyField(blank=True, related_name='list_product', to='core.Product', verbose_name='Thuốc')),
                ('session', models.ManyToManyField(blank=True, related_name='list_session', to='core.Session', verbose_name='Buổi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': '08. Chi tiết các sản phẩm trong Đơn kê',
            },
        ),
    ]
