# Generated by Django 3.2 on 2022-08-04 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_customer_customer_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCustommer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated_at')),
                ('name', models.CharField(max_length=255, verbose_name='Tên loại khách hàng')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mô tả loại khách hàng')),
            ],
            options={
                'verbose_name_plural': '12. Loại khách hàng',
            },
        ),
        migrations.CreateModel(
            name='TypeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated_at')),
                ('name', models.CharField(max_length=255, verbose_name='Tên tình trạng')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mô tả tình trạng')),
            ],
            options={
                'verbose_name_plural': '11. Loại Tình trạng',
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image_profile',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.typestatus', verbose_name='Tình trạng khách hàng'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.typecustommer', verbose_name='Loại khách hàng'),
        ),
    ]
