# Generated by Django 3.2 on 2022-08-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220804_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typestatus',
            options={'verbose_name_plural': '11. Loại Tình trạng khách hàng'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='numberphone',
            field=models.IntegerField(blank=True, max_length=13, null=True, verbose_name='Số điện thoại'),
        ),
    ]
