# Generated by Django 3.2 on 2022-08-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220804_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='CMT/CCCD'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='numberphone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số điện thoại'),
        ),
    ]
