# Generated by Django 3.2 on 2022-08-06 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220805_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='how_to',
            new_name='use_to',
        ),
        migrations.RemoveField(
            model_name='detailorderproduct',
            name='day',
        ),
        migrations.AddField(
            model_name='detailorderproduct',
            name='day',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ngày'),
        ),
        migrations.RemoveField(
            model_name='detailorderproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='detailorderproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='Thuốc'),
        ),
        migrations.RemoveField(
            model_name='detailorderproduct',
            name='session',
        ),
        migrations.AddField(
            model_name='detailorderproduct',
            name='session',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Buổi'),
        ),
        migrations.RemoveField(
            model_name='detailorderservice',
            name='service',
        ),
        migrations.AddField(
            model_name='detailorderservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service', verbose_name='Tên dịch vụ'),
        ),
        migrations.AlterField(
            model_name='detailorderservice',
            name='time',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Thời gian'),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
