# Generated by Django 3.2 on 2022-08-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220806_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated_at')),
                ('buoi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ngày')),
            ],
            options={
                'verbose_name_plural': '12. Buổi',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated_at')),
                ('day', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ngày')),
            ],
            options={
                'verbose_name_plural': '11. Ngày',
            },
        ),
        migrations.RemoveField(
            model_name='detailorderproduct',
            name='session',
        ),
        migrations.AddField(
            model_name='detailorderproduct',
            name='buoi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.buoi', verbose_name='Buổi'),
        ),
        migrations.AlterField(
            model_name='detailorderproduct',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.day', verbose_name='Ngày'),
        ),
    ]
