# Generated by Django 3.2 on 2022-08-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220808_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_re_examination',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày tái khám'),
        ),
        migrations.AlterField(
            model_name='order',
            name='use_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cách dùng'),
        ),
    ]
