# Generated by Django 3.2 on 2022-08-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220808_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compare',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='So sánh'),
        ),
        migrations.AddField(
            model_name='product',
            name='estimate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ước lượng sử dụng'),
        ),
        migrations.AddField(
            model_name='product',
            name='fit',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Phù hợp da'),
        ),
        migrations.AddField(
            model_name='product',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Từ khóa Routine'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dosage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tần suất sử dụng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='function',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Công dụng'),
        ),
    ]
