# Generated by Django 3.2 on 2022-08-12 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220811_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailorderproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='Đơn kê'),
        ),
        migrations.AlterField(
            model_name='detailorderservice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='Đơn kê'),
        ),
        migrations.AlterField(
            model_name='fileorder',
            name='img_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='Hình ảnh đơn kê'),
        ),
    ]
