# Generated by Django 3.2 on 2022-08-13 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220812_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated_at')),
                ('content', models.CharField(max_length=200, verbose_name='Nội dung thông báo')),
                ('is_view', models.BooleanField(default=False, verbose_name='Đã xem')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Đã gửi')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': '13. Thông báo',
            },
        ),
    ]
