# Generated by Django 3.2 on 2022-08-15 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='Khách hàng'),
        ),
    ]
