# Generated by Django 3.2 on 2022-08-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notifications_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='type',
        ),
        migrations.AddField(
            model_name='customer',
            name='household',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hộ khẩu'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tel'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ TT'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='numberphone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Di động'),
        ),
    ]
