# Generated by Django 3.2 on 2022-08-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220817_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=2550, null=True, verbose_name='Địa chỉ TT'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=2550, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='household',
            field=models.CharField(blank=True, max_length=2550, null=True, verbose_name='Hộ khẩu'),
        ),
    ]
