# Generated by Django 3.2 on 2022-08-17 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220817_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='household',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tel',
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tuổi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nghề nghiệp'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.typestatus', verbose_name='Tình trạng khách hàng'),
        ),
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.typecustommer', verbose_name='Loại khách hàng'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Tên khách hàng'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='numberphone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số điện thoại'),
        ),
    ]
