# Generated by Django 3.2 on 2022-08-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220817_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileorder',
            name='file_after',
            field=models.FileField(blank=True, null=True, upload_to='images after/', verbose_name='Hình ảnh sau điều trị'),
        ),
        migrations.AlterField(
            model_name='fileorder',
            name='file_before',
            field=models.FileField(blank=True, null=True, upload_to='images before/', verbose_name='Hình ảnh trước điều trị'),
        ),
    ]
