# Generated by Django 3.2 on 2022-08-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20220817_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailorderproduct',
            name='any_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detailorderservice',
            name='any_service',
            field=models.BooleanField(default=False),
        ),
    ]
