# Generated by Django 3.2 on 2022-08-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20220824_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='numberphone',
            field=models.IntegerField(unique=True, verbose_name='Số điện thoại'),
        ),
    ]
