# Generated by Django 3.2 on 2022-09-09 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_customer_numberphone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typecustommer',
            options={'verbose_name_plural': '12. Nhóm khách hàng'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.typecustommer', verbose_name='Nhóm khách hàng'),
        ),
        migrations.AlterField(
            model_name='typecustommer',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mô tả Nhóm khách hàng'),
        ),
        migrations.AlterField(
            model_name='typecustommer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên Nhóm khách hàng'),
        ),
    ]
