# Generated by Django 3.2 on 2022-09-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20220909_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='code',
        ),
    ]
