# Generated by Django 3.2 on 2022-09-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ghi chú khách hàng'),
        ),
    ]
