# Generated by Django 3.2 on 2022-09-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_customer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ghi chú đơn kê'),
        ),
    ]
