# Generated by Django 3.2 on 2022-09-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_order_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='note',
            new_name='note_order',
        ),
    ]
