# Generated by Django 3.2 on 2022-09-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_note_order_note_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compare',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fit',
        ),
    ]
