# Generated by Django 3.2 on 2022-09-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220909_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileproduct',
            old_name='product_image',
            new_name='file_product',
        ),
        migrations.AlterField(
            model_name='fileproduct',
            name='images_product',
            field=models.FileField(blank=True, null=True, upload_to='images product/', verbose_name='Hình ảnh'),
        ),
    ]
