# Generated by Django 3.2 on 2022-09-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_order_pathological'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dosage',
            field=models.CharField(max_length=255, verbose_name='Tần suất sử dụng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='estimate',
            field=models.CharField(max_length=255, verbose_name='Ước lượng sử dụng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='function',
            field=models.CharField(max_length=1024, verbose_name='Công dụng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keyword',
            field=models.CharField(max_length=255, verbose_name='Từ khóa Routine'),
        ),
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.CharField(max_length=1024, verbose_name='Lưu ý'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Giá'),
        ),
    ]
