# Generated by Django 3.2 on 2022-09-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220912_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='use_to',
            field=models.TextField(blank=True, null=True, verbose_name='Cách dùng'),
        ),
    ]
