# Generated by Django 3.2 on 2022-09-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_order_use_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='detail_caleder_examination',
            field=models.TextField(blank=True, null=True, verbose_name='Chi tiết lịch khám'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note_order',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú đơn kê'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pathological',
            field=models.TextField(blank=True, null=True, verbose_name='Bệnh lý'),
        ),
    ]
